apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: circleguard-master
resources:
  - namespace.yml
  - ../../base
images:
  - name: circleguard-auth-service
    newName: prapoju/circleguard-auth-service
    newTag: stage
  - name: circleguard-identity-service
    newName: prapoju/circleguard-identity-service
    newTag: stage
  - name: circleguard-dashboard-service
    newName: prapoju/circleguard-dashboard-service
    newTag: stage
  - name: circleguard-notification-service
    newName: prapoju/circleguard-notification-service
    newTag: stage
  - name: circleguard-form-service
    newName: prapoju/circleguard-form-service
    newTag: stage
  - name: circleguard-file-service
    newName: prapoju/circleguard-file-service
    newTag: stage
