spring:
  application:
    name: circleguard-file-service

# Placeholder for S3/MinIO configuration if needed later
# aws:
#   s3:
#     endpoint: http://localhost:9000
#     access-key: minioadmin
#     secret-key: minioadmin

server:
  port: 8085

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger-collector:4318/v1/traces}
