apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-service
  template:
    metadata:
      labels:
        app: form-service
    spec:
      containers:
        - name: form-service
          image: circleguard-form-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          readinessProbe:
            tcpSocket:
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/circleguard_form
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: form-service
spec:
  selector:
    app: form-service
  ports:
    - port: 8086
      targetPort: 8086
