apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion-service
  template:
    metadata:
      labels:
        app: promotion-service
    spec:
      initContainers:
        - name: wait-for-neo4j
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z neo4j 7687; do echo waiting for neo4j; sleep 2; done
      serviceAccountName: promotion-service-sa
      containers:
        - name: promotion-service
          image: circleguard-promotion-service
          ports:
            - containerPort: 8088
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/circleguard_promotion
            - name: SPRING_NEO4J_URI
              value: bolt://neo4j:7687
            - name: SPRING_NEO4J_AUTHENTICATION_USERNAME
              value: neo4j
          envFrom:
            - configMapRef:
                name: circleguard-config
            - secretRef:
                name: circleguard-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: promotion-service
spec:
  selector:
    app: promotion-service
  ports:
    - port: 8088
      targetPort: 8088
