apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion-service
  template:
    metadata:
      labels:
        app: promotion-service
    spec:
      containers:
        - name: promotion-service
          image: circleguard-promotion-service
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/circleguard_promotion
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_NEO4J_URI
              value: bolt://neo4j:7687
            - name: SPRING_NEO4J_AUTHENTICATION_USERNAME
              value: neo4j
            - name: SPRING_NEO4J_AUTHENTICATION_PASSWORD
              value: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_DATA_REDIS_HOST
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: promotion-service
spec:
  selector:
    app: promotion-service
  ports:
    - port: 8088
      targetPort: 8088
