apiVersion: v1
kind: ConfigMap
metadata:
  name: circleguard-config
data:
  ENV_NAME: dev
  LOG_LEVEL: INFO
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_LDAP_URLS: ldap://openldap:389
  AUTH_SERVICE_URL: http://auth-service:8180
  IDENTITY_SERVICE_URL: http://identity-service:8083
  PROMOTION_SERVICE_URL: http://promotion-service:8088
