apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: circleguard-stage
resources:
  - namespace.yml
  - ../../base
images:
  - name: circleguard-auth-service
    newName: prapoju/circleguard-auth-service
    newTag: dev
  - name: circleguard-identity-service
    newName: prapoju/circleguard-identity-service
    newTag: dev
  - name: circleguard-promotion-service
    newName: prapoju/circleguard-promotion-service
    newTag: dev
  - name: circleguard-dashboard-service
    newName: prapoju/circleguard-dashboard-service
    newTag: dev
  - name: circleguard-notification-service
    newName: prapoju/circleguard-notification-service
    newTag: dev
  - name: circleguard-form-service
    newName: prapoju/circleguard-form-service
    newTag: dev
  - name: circleguard-file-service
    newName: prapoju/circleguard-file-service
    newTag: dev
  - name: circleguard-gateway-service
    newName: prapoju/circleguard-gateway-service
    newTag: dev
