apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-agents
---
apiVersion: v1
kind: Namespace
metadata:
  name: circleguard-stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: circleguard-master
