spring:
  application:
    name: circleguard-identity-service
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/circleguard_identity
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

vault:
  secret: "746573742d7365637265742d33322d63686172732d6c6f6e672d313233343536"
  salt: "deadbeef"
  hash-salt: "12345678"

jwt:
  secret: "fTgARXTbAm0UJ4Nr4c5pVEUlwNT6qql7ykg43zwhTPI="

server:
  port: 8083

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
      group:
        readiness:
          include: readinessState,db
        liveness:
          include: livenessState
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger-collector:4318/v1/traces}
