spring:
  application:
    name: circleguard-identity-service
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/circleguard_identity
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

vault:
  secret: "746573742d7365637265742d33322d63686172732d6c6f6e672d313233343536"
  salt: "deadbeef"
  hash-salt: "12345678"

jwt:
  secret: "fTgARXTbAm0UJ4Nr4c5pVEUlwNT6qql7ykg43zwhTPI="

server:
  port: 8083
